jquery_lang_js.prototype.lang.es = {
	'Back':'Atrás',
	'Pulmonary valve (PSAX) and aortic valve (PLAX) measured at the hinge points in systole. AV valves (4CV) measured in diastole. Values in cm':'Válvula pulmonar (PEC) y válvula aórtica (PEL) medidas en los puntos de inserción en sístole. Válvulas AV (4C) medidas en diástole. Valores en cm',
	'Tricuspid Annular Peak Systolic Velocity by tissue-doppler, the cursor placed at the lateral side of the tricuspid annulus':'Velocidad Sistólica Pico del Anillo Tricuspídeo por Doppler tisular, el volumen muestra colocado en la porción lateral del anillo tricuspídeo', 
	'Mitral Annular Peak Systolic Velocity by tissue-doppler, the cursor placed at the lateral side of the mitral annulus':'Velocidad Sistólica Pico del Anillo Mitral por Doppler tisular, el volumen muestra colocado en la porción lateral del anillo mitral',
	'Tricuspid Annular Plane Systolic Excursion by m-mode, the cursor placed at the lateral side of the tricuspid annulus':'Excursión Sistólica del Plano del Anillo Tricuspídeo por modo M, el volumen muestra colocado en la porción lateral del anillo tricuspídeo',
	'Mitral Annular Plane Systolic Excursion by m-mode, the cursor placed at the lateral side of the mitral annulus':'Excursión Sistólica del Plano del Anillo Mitral por modo M, el volumen muestra colocado en la porción lateral del anillo mitral',
	'Pulmonary artery diameters in short-axis view. Maximal diameter, LPA  and RPA immediatly after bifurcation':'Diámetros de las arterias pulmonares en vista de eje corto. Diámetro máximo, RIAP y RDAP inmediatamente posterior a la bifurcación',
	'Maximal diameters of the aortic arch (between innominate and left carotid arteries), isthmus (immediately beyond left subclavian artery), distal aortic arch (beyond aortic isthmus), and descending aorta (at the level of diaphragm)':'Diámetros máximos del arco aórtico (entre el tronco braquiocefálico y la arteria carótida izquierda), istmo (inmediatamente posterior a la arteria subclavia izquierda), arco aórtico distal (posterior al istmo aórtico), y aorta descendente (a nivel del diafragma)',
	'MPA':'TAP',
	'FS':'FA',
	'LPA':'RIAP',
	'RPA':'RDAP',
	'RVAWD':'PAVD',
	'RVDD':'DdVD',
	'IVSD':'SIVd',
	'IVSS':'SIVs',
	'LVEDD':'DdVI',
	'LVESD':'DsVI',
	'LVPWD':'PPVId',
	'LVPWS':'PPVIs',
	'PV':'VP',
	'MV':'VM',
	'TV':'VT',
	'AoV':'VAo',
	'Anulus':'Anillo',
	'SoV':'SV',
	'STJ':'UST',
	'AAo':'AoAsc',
	'LMCA':'CI',
	'LAD':'DA',
	'Cx':'Cx',
	'RCAprox':'CDprox',
	'RCAmed':'CDmed',
	'RCAdist':'CDdist',
	'MAPSE':'MAPSE',
	'TAPSE':'TAPSE',
	'MAPSV':'MAPSV',
	'TAPSV':'TAPSV',
	'Transv. arch':'Arco Transv.',
	'Isthmus':'Istmo',
	'Distal arch':'Arco distal',
	'DAo':'AoDesc',
	'Weight/Height':'Peso/Talla',
    'Pulmonary Artery':'Arteria Pulmonar',
	'Valves':'Válvulas',
	'LV/RV function':'Función VI/VD',
	'Coronaries':'Coronarias',
	'Aorta':'Aorta',
	'Output':'Resultados',
	'Optional (for MAPSE/TAPSE)':'Opcional (para MAPSE/TAPSE)',
	'Prefered units':'Unidades de preferencia',
	'Metric':'Métrico',
	'Inch-pound':'Libra-pulgada',
	'Body percentiles': 'Percentiles corporales',
	'Height, weight and more': 'Talla, peso y más',
	'Birth percentiles': 'Percentiles al nacimiento',
	'According to Voigt or Fenton': 'De acuerdo a Voigt o Fenton',
	'Ped(z) - Pediatric calculator': 'Ped(z) - Calculadora pediátrica',
	'BP percentiles': 'Percentiles de TA',
	'Blood pressure percentiles': 'Percentiles de presión arterial',
	'Kidney percentiles': 'Percentiles del riñón',
	'For volume and length': 'Para volumen y longitud',
	'QTc Calculator': 'Calculadora de QTc',
	'Corrected QT interval': 'Intervalo QT corregido',
	'Body Surface Area': 'Área de Superficie Corporal',
	'Mosteller or DuBois': 'Mosteller o DuBois',
	'Perfusor': 'Perfusor',
	'For syringe pumps': 'Para bombas de infusión de jeringas',
	'Date input method': 'Método de entrada de fecha',
	'Gestational age': 'Edad gestacional',
	'Weeks of gestation': 'Semanas de gestación',
	'ECG normal values': 'Valores normales de ECG',
	'From Park/Guntheroth': 'De Park/Guntheroth',
	'Midparental Height': 'Talla media de los padres',
	'Estimated target height': 'Talla diana',
	'Small tool box for pediatricians. Comments and suggestions are welcome': 'Pequeña caja de herramientas para pediatras. Los comentarios y sugerencias son bienvenidos',
	'Heart rate (bpm)': 'Frecuencia cardiaca (lpm)',
	'RR-interval (msec)': 'Intervalo RR (ms)',
	'QT (msec)': 'QT (ms)',
	'HR (bpm)': 'FC (lpm)',
	'RR (msec)': 'RR (ms)',
	'QTc (msec)': 'QTc (ms)',
	'QTc interval according to Bazett (1980)': 'Intervalo QTc de acuerdo a Bazett (1980)',
	'or': 'o',
	'QTc Calculator': 'Calculadora de QTcr',
	'Body Surface Area': 'Área de Superficie Corporal',
	'Height': 'Talla',
	'Weight': 'Peso',
	'Calculations after the Mosteller formula (1987) or DuBois (1916)': 'Cálculos después de la fórmula de Mosteller (1987) o DuBois (1916)',
	'BSA (m2) = sqrt((Height (cm) * Weight (kg)) / 3600)': 'ASC (m2) = sqrt(Talla (m) * Peso (kg) / 3600 )',
	'Close': 'Cerrar',
	'Midparental Height': 'Talla media de los padres',
	'Boy': 'Niño',
	'Girl': 'Niña',
	'Height father': 'Talla del padre',
	'Height mother': 'Talla de la madre',
	'Height child (cm)': 'Talla del niño (cm)',
	'Expected target height for boys or girls according to': 'Talla diana para niños o niñas de acuerdo a',
	'Birth percentiles': 'Percentiles al nacimiento',
	'Weeks': 'Semanas',
	'Days': 'Días',
	'Weight': 'Peso',
	'Length': 'Longitud',
	'Head': 'Cabeza',
	'Weight': 'Peso',
	'Length': 'Longitud',
	'Height': 'Talla',
	'Calculation of birth percentiles according to': 'Cálculo de las percentilas al nacimiento de acuerdo a',
	'The raw data consists of a grid of completed weeks hence values in between two weeks will be interpolated': 'Los datos crudos consisten en un grupo de semanas completas, por lo que los valores entre dos semanas serán interpolados',
	'or alternatively according to': 'o de manera alterna de acuerdo a',
	'The author of this app has a licence for using the Fenton data. A licence can be obtained at tfenton@ucalgary.ca': 'EL autor de esta aplicación tiene licencia para usar los datos de Fenton. Puede obtenerse una licencia en tfenton@ucalgary.ca',
	'Choose your data source under options': 'Escoja la fuente de datos de las opciones',
	'BMI Percentiles': 'Percentiles de IMC',
	'Date of birth': 'Fecha de nacimiento',
	'Current date': 'Fecha actual',
	'BMI': 'IMC',
	'Percentiles for height, weight and BMI according to:': 'Percentiles para talla, peso e IMC de acuerdo a:',
	'Percentiles for head circumference according to:': 'Percentiles para circunferencia cefálica de acuerdo a:',
	'Perfusor': 'Perfusor',
	'Weight': 'Peso',
	'Substance': 'Sustancia',
	'Solved in': 'Diluido en',
	'Rate': 'Tasa',
	'Dosage': 'Dosis',
	'per': 'por',
	'Solve to': 'Para calcular',
	'Clear all': 'Borar todo',
	'Dimensionless Calculator for syringe pumps. Examples': 'Calculadora adimensional para bombas de jeringa. Ejemplos:',
	'Which drug dosage does the patient receive': 'Qué dosis de la sustancia recibe el paciente',
	'Which application rate is needed for the patient getting the designated drug dosage': 'Qué tasa de infusión se necesita para que el paciente reciba la dosis deseada',
	'Which amount of active substance/ingredient must the syringe pump contain, so that if the application rate is 1ml/h the patient receives 0.1/h of the active ingredient': 'Qué cantidad de sustancia activa/ingrediente debe contener la bomba de infusión de jeringa, para que al aplicar a una tasa de 1ml/h el paciente reciba 0.1/h de la sustancia activa',
	'Gestational age': 'Edad gestacional',
	'Due Day (calculated)': 'Fecha de parto (calculada)',
	'Due Day (actual)': 'Fecha de parto (real)',
	'Calculation of the gestational age via calculated and actual due day': 'Cálculo de la edad gestacional por medio de la fecha de parto real y calculada',
	'Blood pressure': 'Presión arterial',
	'Percentiles of blood pressure for children and adolescents according to':'Percentiles de presión arterial para niños y adolescentes de acuerdo a',
	'24h percentiles according to': 'Percentiles de 24 horas de acuerdo a',
	'Kidney': 'Riñón',
	'Volume (ml)': 'Volumen (ml)',
	'Percentiles for kidney length and kidney volume according to': 'Percentiles para longitud renal y volumen renal de acuerdo a',
	'Nighttime values for ': 'Valores nocturnos para',
	'Daytime values for ': 'Valores diurnos para',
	'height percentile': 'Percentil de talla',
	'Age of patient exceeds 18 years': 'La edad del paciente excede los 18 años',
	'Enter size of patient': 'Ingrese el tamaño del paciente',
	'Nighttime': 'Nocturno',
	'Upper limit for mean values': 'Límite superior para los valores promedio',
	'Daytime': 'Diurno',
	'Heart rate': 'Frecuencia cardiaca',
	'ECG normal values for children according to': 'Valores normales del ECG de acuerdo a',
	'QRS interval': 'Intervalo QRS',
	'PQ interval': 'Intervalo PQ',
	'Cardiac z-scores': 'Z-scores cardiacos',
	'Z-Scores (SDS) for pediatric cardiac m mode according to': 'Puntuación Z (SDS) para modo M del corazón pediátrico de acuerdo a',
	'For pediatric echocardiography': 'Para ecocardiografía pediátrica',
	'Body height': 'Talla corporal',
	'Body weight': 'Peso corporal',
	'Length': 'Longitud',
	'Volume': 'Volumen',
	'Body': 'Cuerpo',
	'Prefer KiGGS data': 'De preferencia datos de KiGGS',
	'Prefer Kromeyer-H. data': 'De preferencia datos de Kromeyer-H.',
	'Prefer CDC/WHO data': 'De preferencia datos de CDC/WHO',
	'Prefer AHA data': 'De preferencia datos de la AHA',
	'Prefer obese data':'De preferencia datos de los obesos',
	'Height for obese':'Altura para obesos',
	'Hip': 'Cadera',
	'Waist': 'Cintura',
	'Waist/Hip': 'Cintura/Cadera',
	'Waist/Height': 'Cintura/Talla',
	'Triceps skinfold': 'Pliegue cutáneo del tríceps',
	'Skinfold sum': 'Suma de los pliegues cutáneos',
	'Subscapular skinfold': 'Pliegue cutáneo subescapular',
	'Remaining percentiles (alternatively replacing the ones above)': 'Percentilas restantes (reemplazando alternativamente los anteriores)',
	'Info': 'Info',
	'Gestational age (weeks : days)': 'Edad gestacional (semanas : días)',
	'Options': 'Opciones',
	'Calculated age': 'Edad calculada',
	'years': 'años',
	'Values for the ': 'Valores para ',
	'. percentile': '. percentila',
	'Echocardiographic Z-scores for aortic root parameters according to': 'Puntuación Z para los parámetros de la raíz aórtica de acuerdo a',
	'Aortic anulus': 'Anillo aórtico',
	'Aortic valve': 'Válvula aórtica',
	'Pulmonary valve': 'Válvula pulmonar',
	'Tricuspidal valve': 'Válvula tricúspide',
	'Mitral valve': 'Válvula mitral',
	'Cardiac circumference': 'Circunferencia cardiaca',
	'Aortic root': 'Raíz aórtica',
	'Sinus of Valsalva': 'Senos de Valsalva',
	'Sinotubular junction': 'Unión sinotubular',
	'Ascending aorta': 'Aorta ascendente',
	'Aortic root': 'Raíz aórtica',
	'Correlate with': 'Correlacionar con',
	'Femoral diaphysis length': 'longitud diafisaria del fémur',
	'Menstrual age': 'Edad menstrual',
	'Biparietal diameter': 'Diámetro biparietal',
	'Fetal echocardiography z-scores according to': 'Puntuación Z de ecocardiografía fetal de acuerdo a',
	'Cardiac dimensions': 'Dimensiones cardiacas',
	'Aortic z-scores': 'Punutación Z aórtica',
	'Fetal z-scores': 'Puntuación Z fetal',
	'For prenatal echo': 'Para ecocardiograma prenatal',
	'Aortic Root': 'Raíz aórtica',
	'Fetal echo': 'Ecocardiograma fetal',
	'Body Perc.': 'Perc. corporal',
	'MPH': 'Zielgröße',
	'Neo Perc.': 'Perc. neonatales',
	'GA': 'EG',
	'Aortic Z': 'Z aórtica',
	'Fetal Z': 'Z fetal',
	'BSA': 'ASC',
	'General Pediatrics': 'Pediatría general',
	'Neonatology': 'Neonatología',
	'Dosage': 'Dosis',
	'Cardiac M-Mode measurements in PLAX':'Mediciones cardiacas en modo M en PEL',
	'Diastolic measures of sinuses of Valsalva, sinotubular junction and proximal ascending aorta with leading-edge-to-leading-edge technique. Aortic anulus measured in systole at the hinge point of the aortic leaflets': 'Mediciones en diástole de los senos de Valsalva, unión sinotubular y aorta ascendente proximal con la técnica de borde anterior a borde anterior. Anillo aórtico medido en sístole en el punto de inserción de las valvas aórticas',
	'Cardiology': 'Cardilogía',
	'Pediatric Sonography': 'Ecocardiografía pediátrica',
	'List': 'Lista',
	'Icons': 'Íconos',
	'Prefer Voigt data': 'De preferencia datos de Voigt',
	'Prefer Fenton data': 'De preferencia datos de Fenton',
	'Percentiles according to': 'Percentiles de acuerdo a',
	'The diagram represents following interval': 'El diagrama representa el intervalo siguiente',
	'SSW':'SDG',
	'Diameter of several portions of the coronary arteries, measured inner-edge-to-inner-edge':'Diámetro de varias porciones de las arterias coronarias, medido de borde interno a borde interno',
	'Target height':'Talla diana',
	'Father height':'Talla del padre',
	'Mother height':'Talla de la madre',
	'Choose your country':'Elija su país',
	'Argentina':'Aegentina',
	'Belgium':'Bélgica',
	'Germany':'Alemania',
	'Italy':'Italia',
	'Poland':'Polonia',
	'Sweden':'Suecia',
	'Switzerland':'Suiza',
	'Target height calculation according to':'Cálculo de la talla diana de acuerdo a',
	'National growth references according to':'Referencias nacionales de crecimiento de acuedo a',
	'The values in braces represent the 95% confidence interval. Please choose your country under options':'Los valores en corchetes representan un intervalo de confianza del 95%. Por favor seleccione su país de entre las opciones',
	'Reference values for spirometry according to':'Valores de referencia para espirometría de acuerdo a',
	'Defined between 3y and 95y, FEV075 and FEV075FVC for caucasians between 3y to 7y':'Definido entre 3 y 95 años, VEF075 y VEF075CVF para caucásicos entre 3 y 7 años',
	'Black':'Negro',
	'North east asia':'Noreste de Asia',
	'South east asia':'Sureste de Asia',
	'Other':'Otro',
	'White':'Blanco',
	'Ethnics':'Etnia',
	'Spirometry z-scores':'Puntuación Z de la espirometría',
	'Please choose ethnics from options: Whites including Mexican Americans and Latin Americans of Caucasian origin, African Americans, South East Asians, North East Asians and for Other ethnic groups or people of mixed descent':'Por favor escoja la etnia: Blancos incluyendo Mexicanos y Latinoamericanos de origen caucásico, Afroamericanos, Asiáticos del Sureste, Asiáticos del Noreste y para Otros grupos étnicos o personas con descendencia mixta',
	'Weight/Length':'Peso/Longitud',
	'Age is undefined':'La edad no está definida',
	'Age has to be between 0 and 18 years':'La edad tiene que ser entre 0 y 18 años',
	'Age has to be between 4 months and 18 years':'La edad tiene que ser entre 4 meses y 18 años',
	'Age has to be between 0 and 20 years':'La edad tiene que ser entre 0 y 20 años',
	'Age has to be between 2 and 20 years':'La edad tiene que ser entre 2 y 20 años',
	'Age has to be between 11 and 18 years':'La edad tiene que ser entre 11 y 18 años',
	'Age has to be between 0 and 3 years':'La edad tiene que ser entre 0 y 3 años',
	'Height has to be between 45cm and 121.5cm':'La talla tiene que ser entre 45 cm y 121.5 cm',
	'Gender is undefined':'El género no está definido',
	'has to be greater than 0':'tiene que ser mayor de 0',
	'Head circumference':'Circunferencia cefálica',
	'Waist/Hip ratio':'Proporción Cintura/Cadera',
	'Waist/Height ratio':'Proporción Cintura/Talla',
	'Percentiles according to':'Percentiles de acuerdo a',
	'Bmi':'IMC',
	'Calculation failed':'El cálculo falló',
	'From 3 to 95 years':'De 3 a 95 años',
	'Age has to be between 3 and 95 years':'La edad tiene que ser entre 3 y 95 años',
	'Ethnics is undefined':'La etnia no está definida',
	'FEV1':'VEF1',
	'FVC':'CVF',
	'FEV1/FVC':'VEF1/CVF',
	'FEF75':'FEF75',
	'FEF2575':'FEF2575',
	'FEV075':'VEF075',
	'FEV075/FVC':'VEF075/CVF',
	'Spirometry':'Espirometría',
	'Pulmonolgy':'Neumología',
	'Ethnics':'Etnias',
	'Either femur diaphysis, menstrual age or biparietal diameter is needed':'Se requiere diáfisis femoral, edad menstrual o diámetro biparietal',
	'Weight has to be greater than 2 kg':'El peso debe ser mayor de 2 kg',
	'BSA has to be between 0.25 and 2':'El ASC tiene que ser entre 0.25 y 2',
	'Weight and height are needed':'Se necesitan peso y talla',
	'Pulmonary z-scores according to':'Puntuación Z pulmonar de acuerdo a',
	'Valve z-scores according to':'Puntuación Z valvular de acuerdo a',
	'Coronary z-scores according to':'Puntuación Z coronaria de acuerdo a',
	'Z-scores for LV and RV function parameters according to':'Puntuación Z para parámetros de función del VI y VD de acuerdo a',
	'FVC: forced vital capacity; FEF25-75: forced expiratory flow at 25-75% of FVC, FEF75: forced expiratory flow at 75% FVC; FEV1: forced expiratry volume in 1s':'CVF: capacidad vital forzada; FEF25-75: flujo espiratorio forzado entre 25-75% de la CVF, FEF75: flujo espiratorio forzado al 75% de la CVF; VEF1: volumen espiratrio forzado en 1s',
	'Aortic valve and pulmonary valve in endsystole; Cardiac circumference in enddiastole':'Válvula aórtica y válvula pulmonar en telesístole; Circunferencia cardiaca en telediástole',
	'Limits for intervention for hyperbilirubinemia according to':'Límites para intervención en hiperbilirrubinemia de acuerdo a',
	'AWMF guideline (german)':'Guías AWMF (alemán)',
	'Hyperbilirubinemia':'Hiperbilirrubinemia',
	'Threshold for phototherapy and exchange transfusion':'Umbral para foroterapia y exanguinotransfusión',
	'Bili':'Bilis',
	'Calculation of several somatic percentiles (height, weight, head circumference, BMI etc.) according to':'Cálculo de varias percentilas somáticas (talla, peso, circunferencia cefálica, IMC, etc.) de acuerdo a',
	'Body surface area according to Mosteller (1987) or DuBois (1916)':'Área de superficie corporal de acuerdo a Mosteller (1987) o DuBois (1916)',
	'Z-Scores for pediatric echocardiography according to':'Puntuación Z para ecocardiografía pediátrica de acuerdo a',
	'Spirometric z-scores and normal values according to':'Puntuación Z para espirometría y valores normales de acuerdo a',
	'BSA Formula according to':'Fórmula para ASC de acuerdo a',
	'Kidney length':'Longitud renal',
	'Kidney volume':'Volumen renal',
	'Normal values for kidney length and kidney volume':'Valores normales para longitud renal y volumen renal',
	'Date':'Fecha',
	'Timespan':'Periodo de tiempo',
	'Minutes':'Minutos',
	'Seconds':'Segundos',
	'Years':'Años',
	'Hours':'Horas',
	'Days':'Días',
	'Months':'Meses',
	'From':'De',
	'To':'Para',
	'gestational weeks':'semanas de gestación',
	'EDV':'VTD',
	'ESV':'VTS',
	'EDV/BSA':'VTD/ASC',
	'EF':'FE',
	'SV':'VL',
	'ESV/BSA':'VTS/ASC',
	'SV/BSA':'VL/ASC',
	'Mass':'Masa',
	'Mass/BSA':'Masa/ASC',
	'MRI ventricle':'Ventrículo en RM',
	'Z-Scores for ventricular dimensions in MRI SSFP sequences':'Puntuación Z para dimensiones ventriculares en secuencias SSFP de RM',
	'Male':'Masculino',
	'Female':'Femenino',
	'Right ventricle':'Ventrículo derecho',
	'Left ventricle':'Ventrículo izquierdo',
	'LV parameters based on Simpsons method of discs, normal range in parentheses':'Parámetros del VI basados en el método de discos de Simpson, rango normal entre paréntesis',
	'RV parameters based on Simpsons method of discs, normal range in parentheses':'Parámetros del VD basados en el método de discos de Simpson, rango normal entre paréntesis',
	'Vessel diameters, normal range in parentheses':'Diámetro de los vasis, rango normal entre paréntesis',
	'Annulus':'Anillos',
	'Sinus':'Senos',
	'Z-Scores for aortic dimensions in MRI SSFP sequences':'Puntuación Z para dimensiones aórticas en secuencias SSFP de RM',
	'Ascending aorta':'Aorta ascendente',
	'STJ':'UST',
	'Proximal descending aorta':'Aorta descendente proximal',
	'Descending aorta':'Aorta descendente',
	'Z-Scores for aortic dimensions in patients with corrected TOF':'Puntuación Z para dimensiones aórticas en pacientes operados de TF',
	'Aortic diameters, normal range for TOF patients in parentheses':'Diámetros aórticos, rango normal para pacientes con TF entre paréntesis',
	'Proximal descendens':'Descendente proximal',
	'Distal descendens':'Descendente distal',
	'BCA':'TBC',
	'LSA':'ASI',
	'Adult':'Adulto',
	'Child':'Niño',
	'or adult':'o adulto',
	'BCA: Before Brachiocephalic Artery; LSA: Before Left Subclavian Artery':'TBC: Antes de la Arteria Braquiocefálica; ASI: Antes de la Arteria Subclavia Izquierda',
	'Before LSA':'Antes de la ASI',
	'Before BCA':'Antes del TBC',
	'LV parameters, absolute numbers':'Parámetros del VI, números absolutos',
	'RV parameters, absolute numbers':'Parámetros del VD, números absolutos',
	'The following parameters are required':'Se requieren los siguientes parámetros',
	'Cystatine C':'Cistatina C',
	'Serum creatinine':'Creatinina sérica',
	'Blood urea nitrogen':'Nitrógeno ureico en sangre',
	'Urea':'Urea',
	'Reference':'Referencia',
	'Age':'Edad',
	'Stadium of chronic kidney disease':'Estadio de la enfermedad renal crónica',
	'Normal GFR':'TFG normal',
	'Normal kidney function':'Función renal normal',
	'Mildly reduced kidney function':'Función renal levemente disminuida',
	'Moderately reduced kidney function':'Función renal moderadamente disminuida',
	'Severely reduced kidney function':'Función renal severamente disminuida',
	'Endstage kidney failure':'Enfermedad renal terminal',
	'Only length between 52 cm and 90 cm':'Longtud sólo entre 52 cm y 90 cm',
	'Only length between 49 cm and 93 cm':'Longitud sólo entre 49 cm y 93 cm',
	'Prefer Mb Down data':'De preferencia datos de Mb Down',
	'Parameter not included in original data':'Parámetro no incluido en los datos originales',
	'Calculator for estimated GFR in children an adolescents in cooperation with':'Calculadora para estimar la TFG en niños y adolescentes en cooperación con',
	'University of Erlangen':'Universidad de Erlangen',
	'Department of Paediatrics and Adolescent Medicine':'Departamento de Pediatria y Medicina del Adolescente',
	'Germany':'Alemania',
	'Formula':'Fórmula',
	'Gender':'Género',
	'Percentiles according to':'Percentilas de acuerdo a',
	'Recommended formula':'Fórmula recomendada', // Latest Formula
	'Older formulas':'Fórmulas antiguas',
	'Please note that the genuine formula is not normalized to 1.73 m2 BSA. For your convenience the result in this calculator has already been normalized to BSA':'Por favor note que la fórmula original no está normalizada a 1.73 m2 de ASC. Para su conveniencia el resultado en esta calculadora ya ha sido normalizado para el ASC',
	'Z-Scores for diastolic mean pulmonary dimensions in MRI SSFP sequences':'Puntuación Z para dimensiones diastólicas pulmonares en secuencias SSFP de RM',
	'Vessel diameters':'Diámetros de los vasos',
	'Prefer turkish/german data':'De preferencia datos turcos/alemanes',
	'A summary of GFR formulas for further information can be found':'Se puede encontrar una recopilación de fórmulas para TFG para mayor información',
	'here':'aquí'

}