FROM php:8.2-apache
COPY site.conf /etc/apache2/sites-available/000-default.conf
COPY php.ini /usr/local/etc/php/php.ini
#RUN a2ensite site.conf
RUN apt update 
RUN apt list --upgradable
RUN apt install -y apt-utils libzip-dev zlib1g-dev unzip
RUN apt install -y vim curl wget build-essential software-properties-common git ca-certificates
RUN apt install -y libbz2-dev libfreetype6-dev libjpeg62-turbo-dev libxpm-dev libvpx-dev libmcrypt-dev libmemcached-dev 
RUN apt install -y libjpeg-dev libpng-dev
RUN docker-php-ext-install bcmath bz2 exif gd gettext mysqli pdo_mysql sysvmsg sysvsem sysvshm zip calendar gd
RUN a2enmod headers rewrite
#RUN pecl install mongodb
#RUN docker-php-ext-install mongodb

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
#RUN composer install --ignore-platform-req=ext-gd
#RUN composer require mongodb/mongodb
RUN apt update 
RUN apt-get install -y autoconf pkg-config libssl-dev
RUN pecl install mongodb
RUN docker-php-ext-enable mongodb
RUN composer require mongodb/mongodb --ignore-platform-reqs
RUN composer require jenssegers/mongodb --ignore-platform-reqs
RUN echo "extension=mongodb.so" >> /usr/local/etc/php/conf.d/mongodb.ini

# Add xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug


# Configure Xdebug
RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.log=/var/www/html/xdebug/xdebug.log" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.discover_client_host=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_port=8002" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_host = host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini \
    #&& echo "xdebug.remote_host = 0.0.0.0" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.remote_log=/var/log/xdebug/xdebug.log" >> /usr/local/etc/php/conf.d/xdebug.ini 


RUN apt upgrade --yes
RUN apt autoclean --yes
RUN apt autoremove --yes
RUN rm -rf /var/lib/{apt,dpkg,cache,log}/
